const field = {
        batchno: 'batchno',
        commoditycode: 'commoditycode',
        commodityname: 'commodityname',
        model: 'model',
        packingmeasurement: 'packingmeasurement',
        qty: 'qty',
        packingmeasurementunitname: 'packingmeasurementunitname',
        cargomeasurermentunitname: 'cargomeasurermentunitname',
        piecegrossweight: 'piecegrossweight',
        piecenetweight: 'piecenetweight',
        shelflife: 'shelflife',
        unitprice: 'unitprice',
        productiondate: 'productiondate',
        expirationdate: 'expirationdate',
        snumber: 'snumber',
        planoperationtime: 'planoperationtime',
        remarks: 'remarks',
        storehouseid: 'storehouseid',
        conveywayid: 'conveywayid',
        motorman: 'motorman',
        plateno: 'plateno',
};
export default field;